# Generated by Django 3.2.20 on 2023-08-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocrud', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
